import { useState, useEffect, useRef } from "react";
import { Icon } from "./Icon";
import { type DeckCard, type Draft, swuCardImage } from "../lib/deck";
function CardImage({card,full=false}:{card:DeckCard;full?:boolean}) {
 const [failed,setFailed]=useState(false);
 return failed?<span className="image-fallback">{card.name||card.id}</span>:<img src={swuCardImage(card.id,full)} alt={card.name||"Card "+card.id} loading="lazy" onError={()=>setFailed(true)}/>;
}
export function DeckPanel({draft,loading,busy,onBrowse,onRemove,onRemoveAll,onAdd}:{onRemove:(id:string,section:"deck"|"sideboard",allCopies:boolean)=>void;onRemoveAll:(ids:string[],section:"deck"|"sideboard")=>void;onAdd:(id:string,section:"deck"|"sideboard")=>void;draft:Draft|null;loading:boolean;busy:boolean;onBrowse:()=>void}) {
 const [preview,setPreview]=useState<DeckCard|null>(null),[tab,setTab]=useState<"deck"|"sideboard">("deck");
 const [costFilter,setCostFilter]=useState<number|null>(null);
 useEffect(()=>{setCostFilter(null);setPreview(null);},[draft?.active_deck_id]);
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(preview)dialog.current?.showModal();else dialog.current?.close();},[preview]);
 const deck=draft?.deck_contents;
 if(loading)return <div className="inspector-content" role="status"><div className="deck-skeleton"/><p>Loading your working deck…</p></div>;
 if(!deck)return <div className="inspector-empty"><Icon name="cards" size={40}/><h2>Choose your starting point.</h2><p>Open a saved deck, set a goal, and review the assistant’s suggested changes here.</p><button className="primary-button" onClick={onBrowse}>Browse decks</button></div>;
 const main=deck.deck.reduce((n,c)=>n+c.count,0),side=deck.sideboard.reduce((n,c)=>n+c.count,0);
 const known=deck[tab].filter(c=>c.cost!=null).reduce((n,c)=>n+c.count,0);
 const curve=Array.from({length:8},(_,i)=>deck[tab].filter(c=>c.cost!=null&&(i===7?c.cost>=7:c.cost===i)).reduce((n,c)=>n+c.count,0));
 const max=Math.max(...curve,1);
 const mergedRows:{key:string;card:DeckCard;ids:string[];count:number}[]=[];deck[tab].forEach(c=>{const key=c.name||c.id;const at=mergedRows.findIndex(m=>m.key===key);if(at>=0)mergedRows[at]={...mergedRows[at],count:mergedRows[at].count+c.count,ids:[...mergedRows[at].ids,c.id]};else mergedRows.push({key,card:c,ids:[c.id],count:c.count});});
 const visibleCards=mergedRows.filter(m=>costFilter===null||(m.card.cost!=null&&(costFilter===7?m.card.cost>=7:m.card.cost===costFilter)));
 const types=Object.entries(deck[tab].reduce<Record<string,number>>((all,c)=>{const key=c.type||"Unknown";all[key]=(all[key]||0)+c.count;return all;},{}));
 const copies=Object.values([...deck.deck,...deck.sideboard].reduce<Record<string,number>>((a,c)=>{const k=c.name||c.id;a[k]=(a[k]||0)+c.count;return a;},{})).some(n=>n>3);
 const checks=[!deck.leader&&"Missing leader",!deck.base&&"Missing base",main<50&&"Under 50 main-deck cards",side>10&&"Over 10 sideboard cards",copies&&"Check cards with more than 3 copies"].filter(Boolean);
 return <div className="inspector-content">
  <div className="deck-title-row"><div className="deck-title-copy"><h2 className="deck-title">{draft?.active_deck_name||deck.metadata.name}</h2><div className="deck-summary-line"><strong>{main}</strong> main deck <span>·</span><strong>{side}</strong> sideboard</div></div><div className={"deck-validation "+(checks.length?"is-invalid":"is-valid")} tabIndex={0} role="img" aria-label={checks.length?`Deck checks: ${checks.join("; ")}`:"Basic deck checks passed"}><Icon name={checks.length?"warning":"check"} size={18}/><div className="deck-validation-tooltip" role="tooltip"><strong>{checks.length?"Check before play":"Basic checks passed"}</strong>{checks.length?<ul>{checks.map(check=><li key={String(check)}>{check}</li>)}</ul>:<p>Leader, base, main deck and sideboard counts checked.</p>}<small>Premier baseline only. Format, bans, special card rules and aspect penalties are not verified.</small></div></div></div>
  <div className="identity-grid">{[{card:deck.leader,label:"Leader"},{card:deck.base,label:"Base"}].map(({card,label})=>card&&<button key={card.id} className="identity-card" aria-label={"Inspect "+(card.name||label)} onClick={()=>setPreview(card)}><CardImage card={card} full/></button>)}</div>
  <details className="deck-analysis" open><summary>Resources & card types</summary><div className="curve" aria-label="Printed resource cost distribution">{curve.map((n,i)=><button type="button" key={i} aria-pressed={costFilter===i} onClick={()=>setCostFilter(costFilter===i?null:i)} aria-label={"Filter "+(i===7?"7+":i)+" cost: "+n+" cards"}><span>{n}</span><i style={{height:(n/max*48)+"px"}}/><small>{i===7?"7+":i}</small></button>)}</div><p className="type-distribution">{types.map(([type,n])=><span key={type}>{type} <strong>{n}</strong></span>)}</p>{known<(tab==="deck"?main:side)&&<p className="muted">{(tab==="deck"?main:side)-known} cards have unknown costs.</p>}</details>
  {draft?.proposal&&<p className="muted" role="status">A proposal is waiting for review in the conversation.</p>}
  <div className="deck-tabs" role="tablist" aria-label="Deck section">{(["deck","sideboard"] as const).map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t==="deck"?"Main deck":"Sideboard"} <span>{t==="deck"?main:side}</span></button>)}</div>
  {costFilter!==null&&<div className="cost-filter-status" role="status">Showing {costFilter===7?"7+":costFilter}-cost cards<button className="text-button" onClick={()=>setCostFilter(null)}>Clear cost filter</button></div>}
  <section className="draft-card-list" aria-label={tab==="deck"?"Main deck cards":"Sideboard cards"}>{visibleCards.map(m=><div key={m.key} className="editable-card-row"><button className="draft-card-row" onClick={()=>setPreview(m.card)} aria-label={"Inspect "+(m.card.name||m.key)+", "+m.count+" copies"}><span className="row-count">{m.count}×</span><span className="row-card-image"><CardImage card={m.card}/></span><span className="row-card-name"><strong>{m.card.name||m.key}</strong><small>{m.card.type||"Card details unavailable"}</small></span></button><div className="card-removal"><button disabled={busy} aria-label={"Add one copy of "+(m.card.name||m.key)} title="Add one copy" onMouseDown={e=>e.preventDefault()} onClick={()=>onAdd(m.ids[0],tab)}>+1</button><button disabled={busy} aria-label={"Remove one copy of "+(m.card.name||m.key)} title="Remove one copy" onMouseDown={e=>e.preventDefault()} onClick={()=>onRemove(m.ids[0],tab,false)}>−1</button><button disabled={busy} aria-label={"Remove all copies of "+(m.card.name||m.key)} title="Remove all copies" onMouseDown={e=>e.preventDefault()} onClick={()=>m.ids.length>1?onRemoveAll(m.ids,tab):onRemove(m.ids[0],tab,true)}>Remove</button></div></div>)}{!visibleCards.length&&<p className="muted">{costFilter===null?"No cards in this section.":"No cards at this cost in this section."}</p>}</section>
  <dialog className="card-dialog" ref={dialog} onCancel={()=>setPreview(null)} onClick={e=>{if(e.target===e.currentTarget)setPreview(null);}} aria-label="Card preview"><button autoFocus className="icon-button" aria-label="Close card preview" onClick={()=>setPreview(null)}><Icon name="close"/></button>{preview&&<><CardImage key={preview.id} card={preview} full/><p>{preview.name||preview.id}</p></>}</dialog>
 </div>;
}
